version: "3.9"

services:
  palworld:
    image: palworld
    container_name: palworld
    restart: always
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on host
        protocol: tcp
        mode: host
      - target: 8221 # Service-Portal port inside the container
        published: 8221 # Service-Portal port on host
        protocol: tcp
        mode: host
    volumes:
      #- /opt/palworld/saved:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved #ich hab permission probleme ... # workaround webgui export
      - /opt/palworld/export:/home/steam/export
      - /opt/palworld/conf:/home/steam/conf